# Defines the configuration version.
# The only possible value is "2".
version: "2"

# Options for analysis running.
run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # If the value is lower or equal to 0, the timeout is disabled.
  # Default: 0 (disabled)
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 0
  # Include test files or not.
  # Default: true
  tests: false

# Output configuration options.
output:
  # The formats used to render issues.
  formats:
    # Prints issues in a text format with colors, line number, and linter name.
    text:
      # Output path can be either `stdout`, `stderr` or path to the file to write to.
      path: stdout
    # Prints issues in the Checkstyle format.
    checkstyle:
      # Output path can be either `stdout`, `stderr` or path to the file to write to.
      path: /tmp/lint.out

linters-settings:
  misspell:
    locale: US

  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  disable-all: true
  enable:
    - misspell
    - staticcheck
    - govet
    - revive
    - ineffassign
    - unused
    - prealloc
    - unconvert

formatters:
  enable:
    - goimports
    - gofumpt

issues:
  exclude-use-default: false
  exclude:
      - "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
      - "package-comments: should have a package comment"
      - "exitAfterDefer:"
